version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        http_proxy: http://210.112.194.110:3128
        https_proxy: http://210.112.194.110:3128
    image: ${DOCKER_USER_ID}/flask
  production:
    image: ${DOCKER_USER_ID}/flask:${BUILD_NUMBER}
    volumes:
      - .:/code
    command: python app.py
    ports:
      - "80:80"
